---
kind: pipeline
type: docker
name: k8s-cluster

steps:
      
- name: initialize aws plugin for terraform
  image: mateusmuller2/ansibleandterraform
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret
  commands:
  - terraform init
  
- name: create aws infra
  image: mateusmuller2/ansibleandterraform
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret
  commands:
  - terraform apply -auto-approve

- name: apply ansible playbook
  image: mateusmuller2/ansibleandterraform
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret
  settings:
    playbook: site.yml
    inventory: ec2.py
    private_key:
      from_secret: private_key
  

