---
kind: pipeline
type: docker
name: k8s-cluster

steps:
- name: build ansible and terraform image
  image: mateusmuller2/ansibleandterraform
  environment:
    AWS_ACCESS_KEY_ID: teste
      
- name: initialize aws plugin for terraform
  image: mateusmuller2/ansibleandterraform
  commands:
  - terraform init
  - echo $AWS_ACCESS_KEY_ID
  

